#O application.properties o application.yml pero no los 2
---
spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/Yorso/microspring-config-data.git #Remote GitHub repository
          uri: file://home/jorge/git/microspring9-bus-dynamic-changes-lab8/local-git-repo #Local git repository

  application: 
    name: microspring9-cloud-server-lab8
    
server: 
  port: 8001
  