#O application.properties o application.yml pero no los 2
---
spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/Yorso/microspring-config-data.git #Remote GitHub repository where microspring9-cloud-client-lab8.yml file exists
          uri: file://home/jorge/git/microspring9-bus-dynamic-change-lab8/microspring9-local-git-repository #Local git repository where microspring9-cloud-client-lab8.yml file exists

server: 
  port: 8001
  